document.write("Potência de 3 a 8 - <br>")
document.write(Math.pow(3,8))
document.write("<br><br>Raiz quadrada de 9 - <br>")
document.write(Math.sqrt(9))
document.write("<br><br>O numero inteiro mais perto de 1.6 é - <br>")
document.write(Math.round(1.6))
document.write("<br><br>1.6 arredondado para baixo é - <br>")
document.write(Math.floor(1.6))
document.write("<br><br>1.6 arredondado para cima é - <br>")
document.write(Math.ceil(1.6))
document.write("<br><br>o valor absoluto de 1.6 é - <br>")
document.write(Math.abs(1.6))